### ISSUE TITLE
Error when launching the start-release process

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/issues-manager#84]
When launching the `start-release` process I get the error presented below. The error occurs inside the processing of on of the JIRA issues, it doesn't seem to be the first one.

The error:

```
java.lang.NullPointerException: defaultObj
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at java.base/java.util.Objects.requireNonNullElse(Objects.java:301)
        at dev.snowdrop.release.model.Issue.getKey(Issue.java:92)
        at dev.snowdrop.release.services.IssueService.createIssue(IssueService.java:141)
        at dev.snowdrop.release.services.IssueService.createComponentRequests(IssueService.java:119)
        at dev.snowdrop.release.services.IssueService_ClientProxy.createComponentRequests(IssueService_ClientProxy.zig:256)
        at dev.snowdrop.release.App.startRelease(App.java:169)

```

**Comment by jacobdotcosta** [comment]
Duplicate of #87
