### ISSUE TITLE
dev.snowdrop.release.services.ReleaseFactoryTest is failing with 

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/issues-manager#99]
To reproduce launch `mvn clean package`.

The error is:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running dev.snowdrop.release.services.ReleaseFactoryTest
[ERROR] Tests run: 15, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.586 s <<< FAILURE! - in dev.snowdrop.release.services.ReleaseFactoryTest
[ERROR] creatingFromGitBranchShouldWork  Time elapsed: 0.01 s  <<< ERROR!
java.lang.IllegalArgumentException: Illegal character in path at index 71: https://raw.githubusercontent.com/snowdrop/spring-boot-bom/sb-2.3.x/git remote -vrelease.yml
	at dev.snowdrop.release.services.ReleaseFactoryTest.creatingFromGitBranchShouldWork(ReleaseFactoryTest.java:252)
Caused by: java.net.URISyntaxException: Illegal character in path at index 71: https://raw.githubusercontent.com/snowdrop/spring-boot-bom/sb-2.3.x/git remote -vrelease.yml
	at dev.snowdrop.release.services.ReleaseFactoryTest.creatingFromGitBranchShouldWork(ReleaseFactoryTest.java:252)

```

**Comment by jacobdotcosta** [comment]
This error doesn't occur anymore.
